#!/bin/sh
# Xcode Cloud runs this after cloning, before resolving packages or building.
#
# WHY IT EXISTS: PiDashboard.xcodeproj is generated by XcodeGen from
# ios/PiDashboard/project.yml and is deliberately gitignored (ios/.gitignore:12),
# so it does not exist in a fresh clone. Local builds work because the file is
# already on disk; Xcode Cloud's first two builds failed with
# "Project PiDashboard.xcodeproj does not exist at ios/PiDashboard/PiDashboard.xcodeproj".
# This regenerates it from the tracked recipe so the cloud build has a project.

set -e

echo "--- ci_post_clone: generating Xcode project from project.yml ---"

brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH/ios/PiDashboard"
xcodegen generate

# Fail loudly here rather than letting the build fail later with a vaguer error.
if [ ! -d "PiDashboard.xcodeproj" ]; then
  echo "ERROR: xcodegen ran but PiDashboard.xcodeproj was not produced" >&2
  exit 1
fi

echo "--- ci_post_clone: project generated ---"
ls -d PiDashboard.xcodeproj
