/**
 * Vite plugin for dashboard plugin system.
 *
 * On dev start and build, scans packages/[star]/package.json for pi-dashboard-plugin
 * manifests and generates packages/client/src/generated/plugin-registry.tsx
 * with named imports per claim (enables Vite tree-shaking of unused exports).
 *
 * During dev:
 * - Watches manifest files for changes
 * - Regenerates registry when manifest content hash changes
 * - Triggers HMR (not a full reload)
 *
 * In production:
 * - Skips plugins with fixture: true
 */
import type { Plugin, ViteDevServer } from "vite";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { discoverPlugins, clearDiscoveryCache } from "../server/loader.js";
import { validateManifest } from "../manifest-validator.js";
import type { PluginManifest } from "@blackbelt-technology/pi-dashboard-shared/dashboard-plugin/manifest-types.js";

/** Generated file path (relative to the calling vite.config location). */
const GENERATED_DIR = "packages/client/src/generated";
const GENERATED_FILE = "plugin-registry.tsx";

function getGeneratedPath(repoRoot: string): string {
  return path.join(repoRoot, GENERATED_DIR, GENERATED_FILE);
}

interface PluginEntry {
  manifest: PluginManifest;
  packageDir: string;
  clientEntryPath?: string;
}

function loadPluginEntries(repoRoot: string, isProd: boolean): PluginEntry[] {
  clearDiscoveryCache();
  const discovered = discoverPlugins(repoRoot);
  return discovered
    .filter(p => {
      if (isProd && p.manifest.fixture === true) return false;
      return Boolean(p.clientEntryPath);
    })
    .map(p => ({
      manifest: p.manifest,
      packageDir: p.packageDir,
      clientEntryPath: p.clientEntryPath,
    }));
}

/**
 * Generate the plugin-registry.tsx content using named imports per claim.
 * This form allows Vite to tree-shake unused exports.
 */
function generateRegistryContent(entries: PluginEntry[], repoRoot: string): string {
  const lines: string[] = [
    "// GENERATED — do not edit. Regenerated by viteDashboardPluginsPlugin on every build.",
    "",
  ];

  const generatedDir = path.join(repoRoot, GENERATED_DIR);

  // Named imports per claim component
  for (const entry of entries) {
    // Emit a RELATIVE import path from the generated file's directory to the
    // plugin client entry, so the committed generated file is portable across
    // machines/checkouts. An absolute path bakes in one dev's $HOME — it breaks
    // every other machine's `tsc --noEmit` (TS2307) and re-churns the file on
    // each build. Relative paths are byte-identical everywhere, so the generated
    // file stays stable. Forward-slash + "./"-prefixed for a valid module
    // specifier; extension stripped so tsc (no allowImportingTsExtensions)
    // accepts it (Vite resolves either way via configured extensions).
    const absClientEntry = path.isAbsolute(entry.clientEntryPath!)
      ? entry.clientEntryPath!
      : path.resolve(repoRoot, entry.clientEntryPath!);
    const relRaw = path.relative(generatedDir, absClientEntry).replace(/\.(tsx?|jsx?)$/, "");
    const relPosix = relRaw.split(path.sep).join("/");
    const importPath = relPosix.startsWith(".") ? relPosix : "./" + relPosix;
    const componentNames = [
      ...new Set(
        entry.manifest.claims
          .map(c => c.component)
          .filter((c): c is string => Boolean(c)),
      ),
    ];
    if (componentNames.length > 0) {
      lines.push(
        `import { ${componentNames.join(", ")} } from ${JSON.stringify(importPath)};`,
      );
    }
  }

  lines.push("");
  lines.push("import type { PluginManifest } from \"@blackbelt-technology/pi-dashboard-shared/dashboard-plugin/manifest-types.js\";");
  lines.push("import type { ClaimEntry } from \"@blackbelt-technology/dashboard-plugin-runtime\";");
  lines.push("");
  lines.push("export interface RegistryEntry {");
  lines.push("  manifest: PluginManifest;");
  lines.push("  claims: ClaimEntry[];");
  lines.push("}");
  lines.push("");
  lines.push("export const PLUGIN_REGISTRY: RegistryEntry[] = [");

  for (const entry of entries) {
    const { manifest } = entry;
    lines.push("  {");
    lines.push(`    manifest: ${JSON.stringify(manifest, null, 4).split("\n").join("\n    ")},`);
    lines.push("    claims: [");
    for (const claim of manifest.claims) {
      const componentRef = claim.component ? `, Component: ${claim.component}` : "";
      const tabStr = claim.tab ? `, tab: ${JSON.stringify(claim.tab)}` : "";
      const toolNameStr = claim.toolName ? `, toolName: ${JSON.stringify(claim.toolName)}` : "";
      const commandStr = claim.command ? `, command: ${JSON.stringify(claim.command)}` : "";
      lines.push(
        `      { pluginId: ${JSON.stringify(manifest.id)}, priority: ${manifest.priority ?? 1000}, slot: ${JSON.stringify(claim.slot)}${tabStr}${toolNameStr}${commandStr}${componentRef} },`,
      );
    }
    lines.push("    ],");
    lines.push("  },");
  }

  lines.push("];");
  lines.push("");

  return lines.join("\n");
}

function hashContent(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex").slice(0, 16);
}

let lastHash = "";

function regenerate(repoRoot: string, isProd: boolean): { changed: boolean; content: string } {
  const entries = loadPluginEntries(repoRoot, isProd);
  const content = generateRegistryContent(entries, repoRoot);
  const hash = hashContent(content);

  if (hash === lastHash) return { changed: false, content };

  const outPath = getGeneratedPath(repoRoot);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, "utf-8");
  lastHash = hash;
  return { changed: true, content };
}

/**
 * Returns the Vite plugin for dashboard plugin registry generation.
 * @param repoRoot - Absolute path to the monorepo root. Defaults to process.cwd().
 */
export function viteDashboardPluginsPlugin(repoRoot?: string): Plugin {
  const root = repoRoot ?? process.cwd();

  return {
    name: "vite-dashboard-plugins",
    enforce: "pre", // run before React plugin

    buildStart() {
      const isProd = process.env.NODE_ENV === "production";
      const { changed } = regenerate(root, isProd);
      if (changed) {
        console.info("[vite-dashboard-plugins] Generated plugin-registry.tsx");
      }
    },

    configureServer(server: ViteDevServer) {
      // Watch all packages/*/package.json files for manifest changes
      const packagesDir = path.join(root, "packages");
      if (!fs.existsSync(packagesDir)) return;

      const manifestPaths = fs
        .readdirSync(packagesDir)
        .map(entry => path.join(packagesDir, entry, "package.json"))
        .filter(p => fs.existsSync(p));

      for (const manifestPath of manifestPaths) {
        server.watcher.add(manifestPath);
      }

      server.watcher.on("change", (filePath: string) => {
        if (!manifestPaths.includes(filePath)) return;
        // Check if it's a dashboard plugin manifest
        try {
          const raw = JSON.parse(fs.readFileSync(filePath, "utf-8"));
          if (!raw["pi-dashboard-plugin"]) return;
          // Validate it's still a valid manifest
          try { validateManifest(raw["pi-dashboard-plugin"]); } catch { return; }
        } catch {
          return;
        }

        const { changed } = regenerate(root, false);
        if (changed) {
          console.info("[vite-dashboard-plugins] Manifest changed, regenerated plugin-registry.tsx");
          // Trigger HMR for the generated file
          const generatedPath = getGeneratedPath(root);
          const mod = server.moduleGraph.getModuleById(generatedPath);
          if (mod) {
            server.moduleGraph.invalidateModule(mod);
            server.ws.send({ type: "full-reload" });
          }
        }
      });
    },
  };
}
